disabled_rules:
    - type_body_length
    - strict_fileprivate
    - discarded_notification_center_observer
    - inclusive_language
    - notification_center_detachment
    - orphaned_doc_comment
    - todo
    - unused_capture_list
    - class_delegate_protocol

analyzer_rules:
  - unused_import

opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - colon # promote to error
    - convenience_type
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - fatal_error_message
    - first_where
    - force_unwrapping
    - indentation_width
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - redundant_nil_coalescing
    - redundant_type_annotation
    - strict_fileprivate
    - toggle_bool
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - yoda_condition

attributes:
    always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

cyclomatic_complexity:
    ignores_case_statements: true

force_cast: warning
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
    allowed_symbols: "_"
    excluded:
    - i
    - id
    - x
    - y
    - z
    - vc

indentation_width:
    indentation_width: 4

line_length:
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true

type_name:
    max_length:
        warning: 50
        error: 60
    min_length:
        warning: 1

multiline_arguments:
    first_argument_location: next_line

private_over_fileprivate:
    validate_extensions: true

trailing_whitespace:
    ignores_empty_lines: false
    ignores_comments: true

vertical_whitespace:
    max_empty_lines: 2
